import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/SharedComponents/navigation/Header";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "200"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="w-full overflow-hidden flex flex-col items-center justify-start  mx-auto text-gray-600 px-4 sm:px-10 md:px-10 xl:px-24   ">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
